version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nexthire-db
    environment:
      POSTGRES_USER: nexthire
      POSTGRES_PASSWORD: nexthire_password
      POSTGRES_DB: nexthire_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
