import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { apiClient } from '../api/client';
import { AppHeader } from '../components/layout/AppHeader';
import { AppSidebar } from '../components/layout/AppSidebar';
import { ContestCard } from '../features/contest/components/ContestCard';
import { Trophy, Plus, Key, ArrowRight, Sparkles } from 'lucide-react';
import { useAuthStore } from '../store/useAuthStore';
import { useNotificationStore } from '../store/useNotificationStore';
import { Button } from '../shared/components/ui/Button';

export const ContestsPage: React.FC = () => {
  const [joinCode, setJoinCode] = useState('');
  const { user } = useAuthStore();
  const { addToast } = useNotificationStore();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const isAdmin = user?.role === 'ADMIN';

  const { data, isLoading, isError } = useQuery({
    queryKey: ['contests'],
    queryFn: () => apiClient.get('/contests')
  });

  const joinMutation = useMutation({
    mutationFn: (code: string) => apiClient.post('/contests/join-by-code', { code }),
    onSuccess: (res: any) => {
      const contestId = res.data?.contestId || res.data?.contest?.id;
      addToast('Assessment Joined', 'Successfully registered for assessment session', 'success');
      queryClient.invalidateQueries({ queryKey: ['contests'] });
      navigate(`/contest/${contestId}`);
    },
    onError: (err: any) => {
      addToast('Join Failed', err?.message || 'Invalid or expired assessment join code', 'error');
    }
  });

  const handleJoinByCode = (e: React.FormEvent) => {
    e.preventDefault();
    if (!joinCode.trim()) return;
    joinMutation.mutate(joinCode.trim());
  };

  const contests = data?.data || [];

  return (
    <div className="min-h-screen bg-surface">
      <AppSidebar />
      <AppHeader />

      <main className="ml-[260px] pt-16 p-8 space-y-8 max-w-container-max mx-auto">
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold text-on-surface flex items-center gap-2">
              <Trophy className="w-6 h-6 text-primary" /> DSA Coding Assessments & Sprints
            </h1>
            <p className="text-sm text-on-surface-variant">Host local coding contests, join via unique assessment codes, and track real-time leaderboards.</p>
          </div>

          <Link to="/admin/contests/create">
            <Button variant="primary" className="bg-primary hover:bg-blue-700">
              <Plus className="w-4 h-4" /> Create New Assessment
            </Button>
          </Link>
        </div>

        {/* Join by Code Card */}
        <div className="bg-white border border-primary/20 rounded-3xl p-6 shadow-sm bg-gradient-to-r from-blue-50/50 to-purple-50/50 flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="space-y-1 max-w-md">
            <div className="inline-flex items-center gap-1.5 px-3 py-0.5 bg-blue-100 text-blue-800 rounded-full text-xs font-bold">
              <Key className="w-3.5 h-3.5" /> Participant Quick Join
            </div>
            <h3 className="font-bold text-lg text-slate-900">Have a Private Join Code?</h3>
            <p className="text-xs text-slate-600">Enter the unique assessment join code generated by your contest host to enter the live interview IDE.</p>
          </div>

          <form onSubmit={handleJoinByCode} className="flex items-center gap-3 w-full md:w-auto">
            <input
              type="text"
              required
              value={joinCode}
              onChange={(e) => setJoinCode(e.target.value.toUpperCase())}
              placeholder="e.g. DSA-X9Y2"
              className="px-4 py-3 bg-white border border-slate-300 focus:border-primary rounded-xl text-sm font-mono font-bold uppercase tracking-wider outline-none w-44 shadow-sm"
            />
            <Button type="submit" isLoading={joinMutation.isPending} className="whitespace-nowrap" size="md">
              <span>Join Session</span>
              <ArrowRight className="w-4 h-4" />
            </Button>
          </form>
        </div>

        {/* Contests Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {isLoading ? (
            <p className="text-xs text-slate-500">Loading active assessment sessions...</p>
          ) : isError ? (
            <p className="text-xs text-red-500">Failed to load assessments.</p>
          ) : contests.length === 0 ? (
            <p className="text-xs text-slate-500 py-8 text-center col-span-2">No active assessments found. Click "Create New Assessment" above to host a local session.</p>
          ) : (
            contests.map((c: any) => (
              <ContestCard key={c.id} contest={c} />
            ))
          )}
        </div>
      </main>
    </div>
  );
};
